### ISSUE TITLE
Change property pixeldata to data

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/ProperImage#14]
I think the method returning the `ndarray` pixels from SingleImage should be just `data` instead of `pixeldata`, since that seems to be the standard in masked `numpy` arrays, `CCDData`, `NDData` and `HDUList`.

Likewise it should have a property `mask` that returns the mask as a `ndarray`, but I think that is already implemented.

I don't know what you guys think.

**Comment by martinberoiz** [comment]
Oh, and the `__init__` method should have the keyword `data` for the `ndarray` instead of `img` as it is now.

**Comment by BrunoSanchez** [comment]
Would you prefer that `mask` is a property separated or that `data` is a _masked_ array?

**Comment by martinberoiz** [comment]
I think that `data` should return a plain `ndarray` (no mask) and `mask` return just the mask.
So, yes, the *property* `mask` to be separated from `data`, but internally you can keep them as a masked array, as long as this isn't exposed publicly.

BTW I think this change would break API.
