### ISSUE TITLE
Improve coverage to >= 80%

### ISSUE THREAD

**Issue by leliel12** [toros-astro/ProperImage#31]
We need to improve the coverage of the project to at least to 80%.

Because Pareto. :smile:

**Comment by BrunoSanchez** [comment]
We are close this numbers now. 
I would suggest resolve this issue, but create a new one with 90% requirement.

**Comment by BrunoSanchez** [comment]
I am pushing this issue in a new branch called `streamlined`.
This is going to be a stripped down codebase, that only includes what we are needing.

**Comment by BrunoSanchez** [comment]
We are past this 80%.

Do you think we should close it and open a 90% issue?

**Comment by martinberoiz** [comment]
I think we are good to close it. As to the 90% that's a good goal to achieve, maybe for future releases.

**Comment by BrunoSanchez** [comment]
Great then. Let's move this out of the board for now.
