### ISSUE TITLE
`.plot` accessor

### ISSUE THREAD

**Issue by leliel12** [toros-astro/ProperImage#33]
Provide a accessor to the most common plot of the image through a `plot` accesor attribute.

So instead of run (*img* is a SingleImage instance)

```python
plt.imshow(img)
```
we can use

```python
img.plot() 
# or
img.plot.imshow()
```

Another method can be `img.plot.background()`

**Comment by martinberoiz** [comment]
Is this assuming `img` as a `SingleImage` instance?  Sounds reasonable thing to have.
