### ISSUE TITLE
Remove six from dependencies

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/ProperImage#49]
If we're dropping support for py2.7 (are we?) we can remove the dependency for `six`.
It's used only to import `range` in `single_image` and `single_image_psfs`.

**Comment by BrunoSanchez** [comment]
This is right. Let me do it.

**Comment by BrunoSanchez** [comment]
Fixed already with commit fa9baf430b0f77a9b33ca0ec80725773d6ce34fd
