### ISSUE TITLE
Not sure about these lines

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/ProperImage#59]
I think these lines should not be there? I never used ipdb, so not sure what they do.

https://github.com/toros-astro/ProperImage/blob/4689c8d8fb3f62dc02dcac609c702b4711c723d5/properimage/propersubtract.py#L105-L109

and

https://github.com/toros-astro/ProperImage/blob/4689c8d8fb3f62dc02dcac609c702b4711c723d5/properimage/propersubtract.py#L149-L152

**Comment by BrunoSanchez** [comment]
First lines would deserve a special type of error. 
That's regarding the aligning procedure. If it delivers arrays of different size for _new_ and _reference_ images.

Second group of lines are referring to PSF centroids, controlling they fall in positive value coordinates. We could have a contingency plan, so we don't raise a new type of error, but this shouldn't happen in theory.
