### ISSUE TITLE
Drop astroML dependency

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/ProperImage#65]
Use crossmatch from astropy to drop astroML dependency.

Used in `utils.py`

https://github.com/toros-astro/ProperImage/blob/f4e78943cc1306ec464c6cc8e688b57b55d9b64a/properimage/utils.py#L45

and in no other file.

**Comment by martinberoiz** [comment]
Seems like astropy's cross matching doesn't allow for cross-matching in x, y.
This is the relevant code from astroML:

    X1 = np.asarray(X1, dtype=float)
    X2 = np.asarray(X2, dtype=float)

    N1, D = X1.shape
    N2, D2 = X2.shape

    if D != D2:
        raise ValueError('Arrays must have the same second dimension')

    kdt = cKDTree(X2)

    dist, ind = kdt.query(X1, k=1, distance_upper_bound=max_distance)

    return dist, ind

**Comment by BrunoSanchez** [comment]
We will implement this directly.
